apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  selector:
    matchLabels:
      app: elasticsearch
  replicas: 1
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      volumes:
        - name: elastic-volume
          emptyDir: {}
#          persistentVolumeClaim:
#            claimName: elastic-pvc
      initContainers:
      - name: vm-max-fix
        image: busybox
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: elasticsearch
        image: elasticsearch:7.17.18
        # image: docker.elastic.co/elasticsearch/elasticsearch:7.13.3
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9200
        env:
        #- name: ELASTIC_PASSWORD
        #  value: "123"
        - name: discovery.type
          value: "single-node"
        - name: ES_JAVA_OPTS
          value: -Xms1024m -Xmx1024m
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.authc.api_key.enabled
          value: "true"
        resources:
          limits:
            cpu: 2
            memory: 2350Mi
          requests:
            cpu: 100m
            memory: 2000Mi
        volumeMounts:
        - name: elastic-volume
          mountPath: /usr/share/elasticsearch/data
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - protocol: TCP
      name: http
      port: 9200
      targetPort: 9200
