---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-csi
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.168.32
  share: /mnt/HD/HD_a2/k8s-nfs-csi
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - hard
  - nolock
  #- nfsvers=4.1